/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingapp;

import javax.swing.JOptionPane;

/**
 *
 * @author msull1
 */
public class BankGUI extends javax.swing.JFrame {
    String name;
    float balance;
    float debt;
    CheckingAccount acc1 = new CheckingAccount(name, balance, debt);
    
    /**
     * Creates new form BankGUI
     */
    public BankGUI(String name, float balance, float debt) {
        initComponents();
        acc1.name = name;
        acc1.balance = balance;
        acc1.debt = debt;
        UsernameText.setText(name);
        BalanceText.setText(String.valueOf(balance));
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        BankLabel = new javax.swing.JLabel();
        UsernameText = new javax.swing.JTextField();
        UserLabel = new javax.swing.JLabel();
        BalanceText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ConfirmText = new javax.swing.JTextField();
        DepositConfirm = new javax.swing.JButton();
        DepositClear = new javax.swing.JButton();
        WithdrawConfirm = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LoanConfirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        DebtText = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BankLabel.setBackground(new java.awt.Color(204, 204, 204));
        BankLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BankLabel.setForeground(new java.awt.Color(0, 51, 153));
        BankLabel.setText("Bank Inc. Checking");

        UsernameText.setEditable(false);
        UsernameText.setForeground(new java.awt.Color(0, 51, 153));
        UsernameText.setText("jTextField4");
        UsernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextActionPerformed(evt);
            }
        });

        UserLabel.setForeground(new java.awt.Color(0, 51, 153));
        UserLabel.setText("User:");

        BalanceText.setEditable(false);
        BalanceText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BalanceText.setForeground(new java.awt.Color(0, 51, 153));
        BalanceText.setText("0");
        BalanceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Balance:");

        ConfirmText.setBackground(new java.awt.Color(242, 242, 242));
        ConfirmText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ConfirmText.setForeground(new java.awt.Color(0, 51, 153));
        ConfirmText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ConfirmText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmTextActionPerformed(evt);
            }
        });

        DepositConfirm.setBackground(new java.awt.Color(242, 242, 242));
        DepositConfirm.setForeground(new java.awt.Color(0, 51, 153));
        DepositConfirm.setText("Deposit");
        DepositConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositConfirmActionPerformed(evt);
            }
        });

        DepositClear.setBackground(new java.awt.Color(242, 242, 242));
        DepositClear.setForeground(new java.awt.Color(0, 51, 153));
        DepositClear.setText("Clear");
        DepositClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositClearActionPerformed(evt);
            }
        });

        WithdrawConfirm.setBackground(new java.awt.Color(242, 242, 242));
        WithdrawConfirm.setForeground(new java.awt.Color(0, 51, 153));
        WithdrawConfirm.setText("Withdraw");
        WithdrawConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawConfirmActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Savings Account:");

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setForeground(new java.awt.Color(0, 51, 153));
        jButton3.setText("Go");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(242, 242, 242));
        ExitButton.setForeground(new java.awt.Color(0, 51, 153));
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Add Interest:");

        LoanConfirm.setBackground(new java.awt.Color(242, 242, 242));
        LoanConfirm.setForeground(new java.awt.Color(0, 51, 153));
        LoanConfirm.setText("Loan");
        LoanConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanConfirmActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Debt:");

        DebtText.setEditable(false);
        DebtText.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConfirmText)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BankLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(UserLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ExitButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DepositConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(WithdrawConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LoanConfirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DepositClear)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DebtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DepositClear, DepositConfirm, ExitButton, LoanConfirm, WithdrawConfirm, jButton1, jButton3});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BalanceText, DebtText});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserLabel))
                    .addComponent(BankLabel))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(DebtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(ConfirmText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WithdrawConfirm)
                    .addComponent(DepositClear)
                    .addComponent(DepositConfirm)
                    .addComponent(LoanConfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addComponent(ExitButton)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DepositClear, DepositConfirm, ExitButton, LoanConfirm, WithdrawConfirm, jButton3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Savings(acc1.name, acc1.balance, 0).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ConfirmTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmTextActionPerformed

    private void DepositConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositConfirmActionPerformed
        // TODO add your handling code here:
        acc1.CheckDebt(Float.parseFloat(ConfirmText.getText()));
        BalanceText.setText(String.valueOf(acc1.balance));
        DebtText.setText(String.valueOf(acc1.debt));
        
    }//GEN-LAST:event_DepositConfirmActionPerformed

    private void BalanceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceTextActionPerformed

    private void WithdrawConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawConfirmActionPerformed
        // TODO add your handling code here:
        if (acc1.withdrawl(Float.parseFloat(ConfirmText.getText())) == true){
                   JOptionPane.showMessageDialog(null, "Insufficient Funds");
        }
        BalanceText.setText(String.valueOf(acc1.balance));
    }//GEN-LAST:event_WithdrawConfirmActionPerformed

    private void DepositClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositClearActionPerformed
        // TODO add your handling code here:
        ConfirmText.setText("");
    }//GEN-LAST:event_DepositClearActionPerformed

    private void UsernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        acc1.balance = acc1.Interest(acc1.getBalance(), 1.03f);
        acc1.debt = acc1.Interest(acc1.debt, 1.1f);
        acc1.round();
        BalanceText.setText(String.valueOf(acc1.balance));
        DebtText.setText(String.valueOf(acc1.debt));   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LoanConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanConfirmActionPerformed
        // TODO add your handling code here:
        acc1.AddLoan(Float.parseFloat(ConfirmText.getText())) ;
        acc1.round();
        BalanceText.setText(String.valueOf(acc1.balance));
        DebtText.setText(String.valueOf(acc1.debt));
    }//GEN-LAST:event_LoanConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BalanceText;
    private javax.swing.JLabel BankLabel;
    private javax.swing.JTextField ConfirmText;
    private javax.swing.JTextField DebtText;
    private javax.swing.JButton DepositClear;
    private javax.swing.JButton DepositConfirm;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton LoanConfirm;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JButton WithdrawConfirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
